version: "3.8"

services:
  pocketbase:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
      args:
        PB_VERSION: "0.28.2"
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/app/pocketbase
    restart: unless-stopped
